// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Buildable.proto

package mineralchem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Buildable struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	DiscreteWidth        int32    `protobuf:"varint,3,opt,name=discreteWidth,proto3" json:"discreteWidth,omitempty"`
	DiscreteHeight       int32    `protobuf:"varint,4,opt,name=discreteHeight,proto3" json:"discreteHeight,omitempty"`
	DisplayName          string   `protobuf:"bytes,5,opt,name=displayName,proto3" json:"displayName,omitempty"`
	AutoCollect          int32    `protobuf:"varint,6,opt,name=autoCollect,proto3" json:"autoCollect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Buildable) Reset()         { *m = Buildable{} }
func (m *Buildable) String() string { return proto.CompactTextString(m) }
func (*Buildable) ProtoMessage()    {}
func (*Buildable) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{0}
}

func (m *Buildable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Buildable.Unmarshal(m, b)
}
func (m *Buildable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Buildable.Marshal(b, m, deterministic)
}
func (m *Buildable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buildable.Merge(m, src)
}
func (m *Buildable) XXX_Size() int {
	return xxx_messageInfo_Buildable.Size(m)
}
func (m *Buildable) XXX_DiscardUnknown() {
	xxx_messageInfo_Buildable.DiscardUnknown(m)
}

var xxx_messageInfo_Buildable proto.InternalMessageInfo

func (m *Buildable) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Buildable) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Buildable) GetDiscreteWidth() int32 {
	if m != nil {
		return m.DiscreteWidth
	}
	return 0
}

func (m *Buildable) GetDiscreteHeight() int32 {
	if m != nil {
		return m.DiscreteHeight
	}
	return 0
}

func (m *Buildable) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Buildable) GetAutoCollect() int32 {
	if m != nil {
		return m.AutoCollect
	}
	return 0
}

type BuildableLevelBinding struct {
	Id                                        int32                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Buildable                                 *Buildable                  `protobuf:"bytes,2,opt,name=buildable,proto3" json:"buildable,omitempty"`
	Level                                     int32                       `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	BuildingOrUpgradingDuration               int32                       `protobuf:"varint,4,opt,name=buildingOrUpgradingDuration,proto3" json:"buildingOrUpgradingDuration,omitempty"`
	BuildingOrUpgradingRequiredGold           int32                       `protobuf:"varint,5,opt,name=buildingOrUpgradingRequiredGold,proto3" json:"buildingOrUpgradingRequiredGold,omitempty"`
	BuildingOrUpgradingRequiredResidentsCount int32                       `protobuf:"varint,6,opt,name=buildingOrUpgradingRequiredResidentsCount,proto3" json:"buildingOrUpgradingRequiredResidentsCount,omitempty"`
	BaseGoldProductionRate                    float64                     `protobuf:"fixed64,7,opt,name=baseGoldProductionRate,proto3" json:"baseGoldProductionRate,omitempty"`
	BaseFoodProductionRate                    int32                       `protobuf:"varint,8,opt,name=baseFoodProductionRate,proto3" json:"baseFoodProductionRate,omitempty"`
	BaseRiflemanProductionRequiredGold        int32                       `protobuf:"varint,9,opt,name=baseRiflemanProductionRequiredGold,proto3" json:"baseRiflemanProductionRequiredGold,omitempty"`
	BaseRiflemanProductionDuration            int32                       `protobuf:"varint,10,opt,name=baseRiflemanProductionDuration,proto3" json:"baseRiflemanProductionDuration,omitempty"`
	Dependency                                []*BuildableLevelDependency `protobuf:"bytes,11,rep,name=dependency,proto3" json:"dependency,omitempty"`
	GoldLimitAddition                         int32                       `protobuf:"varint,12,opt,name=goldLimitAddition,proto3" json:"goldLimitAddition,omitempty"`
	BaseHp                                    int32                       `protobuf:"varint,13,opt,name=baseHp,proto3" json:"baseHp,omitempty"`
	BaseDamage                                int32                       `protobuf:"varint,14,opt,name=baseDamage,proto3" json:"baseDamage,omitempty"`
	XXX_NoUnkeyedLiteral                      struct{}                    `json:"-"`
	XXX_unrecognized                          []byte                      `json:"-"`
	XXX_sizecache                             int32                       `json:"-"`
}

func (m *BuildableLevelBinding) Reset()         { *m = BuildableLevelBinding{} }
func (m *BuildableLevelBinding) String() string { return proto.CompactTextString(m) }
func (*BuildableLevelBinding) ProtoMessage()    {}
func (*BuildableLevelBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{1}
}

func (m *BuildableLevelBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildableLevelBinding.Unmarshal(m, b)
}
func (m *BuildableLevelBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildableLevelBinding.Marshal(b, m, deterministic)
}
func (m *BuildableLevelBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildableLevelBinding.Merge(m, src)
}
func (m *BuildableLevelBinding) XXX_Size() int {
	return xxx_messageInfo_BuildableLevelBinding.Size(m)
}
func (m *BuildableLevelBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildableLevelBinding.DiscardUnknown(m)
}

var xxx_messageInfo_BuildableLevelBinding proto.InternalMessageInfo

func (m *BuildableLevelBinding) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuildableLevelBinding) GetBuildable() *Buildable {
	if m != nil {
		return m.Buildable
	}
	return nil
}

func (m *BuildableLevelBinding) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *BuildableLevelBinding) GetBuildingOrUpgradingDuration() int32 {
	if m != nil {
		return m.BuildingOrUpgradingDuration
	}
	return 0
}

func (m *BuildableLevelBinding) GetBuildingOrUpgradingRequiredGold() int32 {
	if m != nil {
		return m.BuildingOrUpgradingRequiredGold
	}
	return 0
}

func (m *BuildableLevelBinding) GetBuildingOrUpgradingRequiredResidentsCount() int32 {
	if m != nil {
		return m.BuildingOrUpgradingRequiredResidentsCount
	}
	return 0
}

func (m *BuildableLevelBinding) GetBaseGoldProductionRate() float64 {
	if m != nil {
		return m.BaseGoldProductionRate
	}
	return 0
}

func (m *BuildableLevelBinding) GetBaseFoodProductionRate() int32 {
	if m != nil {
		return m.BaseFoodProductionRate
	}
	return 0
}

func (m *BuildableLevelBinding) GetBaseRiflemanProductionRequiredGold() int32 {
	if m != nil {
		return m.BaseRiflemanProductionRequiredGold
	}
	return 0
}

func (m *BuildableLevelBinding) GetBaseRiflemanProductionDuration() int32 {
	if m != nil {
		return m.BaseRiflemanProductionDuration
	}
	return 0
}

func (m *BuildableLevelBinding) GetDependency() []*BuildableLevelDependency {
	if m != nil {
		return m.Dependency
	}
	return nil
}

func (m *BuildableLevelBinding) GetGoldLimitAddition() int32 {
	if m != nil {
		return m.GoldLimitAddition
	}
	return 0
}

func (m *BuildableLevelBinding) GetBaseHp() int32 {
	if m != nil {
		return m.BaseHp
	}
	return 0
}

func (m *BuildableLevelBinding) GetBaseDamage() int32 {
	if m != nil {
		return m.BaseDamage
	}
	return 0
}

type BuildableLevelDependency struct {
	RequiredBuildableId     int32    `protobuf:"varint,1,opt,name=requiredBuildableId,proto3" json:"requiredBuildableId,omitempty"`
	RequiredBuildableCount  int32    `protobuf:"varint,2,opt,name=requiredBuildableCount,proto3" json:"requiredBuildableCount,omitempty"`
	RequiredMinimumLevel    int32    `protobuf:"varint,3,opt,name=requiredMinimumLevel,proto3" json:"requiredMinimumLevel,omitempty"`
	TargetBuildableMaxCount int32    `protobuf:"varint,4,opt,name=targetBuildableMaxCount,proto3" json:"targetBuildableMaxCount,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *BuildableLevelDependency) Reset()         { *m = BuildableLevelDependency{} }
func (m *BuildableLevelDependency) String() string { return proto.CompactTextString(m) }
func (*BuildableLevelDependency) ProtoMessage()    {}
func (*BuildableLevelDependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{2}
}

func (m *BuildableLevelDependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildableLevelDependency.Unmarshal(m, b)
}
func (m *BuildableLevelDependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildableLevelDependency.Marshal(b, m, deterministic)
}
func (m *BuildableLevelDependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildableLevelDependency.Merge(m, src)
}
func (m *BuildableLevelDependency) XXX_Size() int {
	return xxx_messageInfo_BuildableLevelDependency.Size(m)
}
func (m *BuildableLevelDependency) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildableLevelDependency.DiscardUnknown(m)
}

var xxx_messageInfo_BuildableLevelDependency proto.InternalMessageInfo

func (m *BuildableLevelDependency) GetRequiredBuildableId() int32 {
	if m != nil {
		return m.RequiredBuildableId
	}
	return 0
}

func (m *BuildableLevelDependency) GetRequiredBuildableCount() int32 {
	if m != nil {
		return m.RequiredBuildableCount
	}
	return 0
}

func (m *BuildableLevelDependency) GetRequiredMinimumLevel() int32 {
	if m != nil {
		return m.RequiredMinimumLevel
	}
	return 0
}

func (m *BuildableLevelDependency) GetTargetBuildableMaxCount() int32 {
	if m != nil {
		return m.TargetBuildableMaxCount
	}
	return 0
}

type BuildableIngredientInteraction struct {
	Id                                int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BuildableId                       int32    `protobuf:"varint,2,opt,name=buildableId,proto3" json:"buildableId,omitempty"`
	IngredientId                      int32    `protobuf:"varint,3,opt,name=ingredientId,proto3" json:"ingredientId,omitempty"`
	Type                              int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	BuildableLevelToUnlockDisplayName int32    `protobuf:"varint,5,opt,name=buildableLevelToUnlockDisplayName,proto3" json:"buildableLevelToUnlockDisplayName,omitempty"`
	RecipeId                          int32    `protobuf:"varint,6,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	IngredientPurchasePriceCurrency   int32    `protobuf:"varint,7,opt,name=ingredientPurchasePriceCurrency,proto3" json:"ingredientPurchasePriceCurrency,omitempty"`
	IngredientPurchasePriceValue      int32    `protobuf:"varint,8,opt,name=ingredientPurchasePriceValue,proto3" json:"ingredientPurchasePriceValue,omitempty"`
	XXX_NoUnkeyedLiteral              struct{} `json:"-"`
	XXX_unrecognized                  []byte   `json:"-"`
	XXX_sizecache                     int32    `json:"-"`
}

func (m *BuildableIngredientInteraction) Reset()         { *m = BuildableIngredientInteraction{} }
func (m *BuildableIngredientInteraction) String() string { return proto.CompactTextString(m) }
func (*BuildableIngredientInteraction) ProtoMessage()    {}
func (*BuildableIngredientInteraction) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{3}
}

func (m *BuildableIngredientInteraction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildableIngredientInteraction.Unmarshal(m, b)
}
func (m *BuildableIngredientInteraction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildableIngredientInteraction.Marshal(b, m, deterministic)
}
func (m *BuildableIngredientInteraction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildableIngredientInteraction.Merge(m, src)
}
func (m *BuildableIngredientInteraction) XXX_Size() int {
	return xxx_messageInfo_BuildableIngredientInteraction.Size(m)
}
func (m *BuildableIngredientInteraction) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildableIngredientInteraction.DiscardUnknown(m)
}

var xxx_messageInfo_BuildableIngredientInteraction proto.InternalMessageInfo

func (m *BuildableIngredientInteraction) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuildableIngredientInteraction) GetBuildableId() int32 {
	if m != nil {
		return m.BuildableId
	}
	return 0
}

func (m *BuildableIngredientInteraction) GetIngredientId() int32 {
	if m != nil {
		return m.IngredientId
	}
	return 0
}

func (m *BuildableIngredientInteraction) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BuildableIngredientInteraction) GetBuildableLevelToUnlockDisplayName() int32 {
	if m != nil {
		return m.BuildableLevelToUnlockDisplayName
	}
	return 0
}

func (m *BuildableIngredientInteraction) GetRecipeId() int32 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

func (m *BuildableIngredientInteraction) GetIngredientPurchasePriceCurrency() int32 {
	if m != nil {
		return m.IngredientPurchasePriceCurrency
	}
	return 0
}

func (m *BuildableIngredientInteraction) GetIngredientPurchasePriceValue() int32 {
	if m != nil {
		return m.IngredientPurchasePriceValue
	}
	return 0
}

type PlayerBuildableBinding struct {
	Id                                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopmostTileDiscretePositionX         int32      `protobuf:"varint,2,opt,name=topmostTileDiscretePositionX,proto3" json:"topmostTileDiscretePositionX,omitempty"`
	TopmostTileDiscretePositionY         int32      `protobuf:"varint,3,opt,name=topmostTileDiscretePositionY,proto3" json:"topmostTileDiscretePositionY,omitempty"`
	PlayerId                             int32      `protobuf:"varint,4,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Buildable                            *Buildable `protobuf:"bytes,5,opt,name=buildable,proto3" json:"buildable,omitempty"`
	CurrentLevel                         int32      `protobuf:"varint,6,opt,name=currentLevel,proto3" json:"currentLevel,omitempty"`
	State                                int32      `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	BuildingOrUpgradingStartedAt         int64      `protobuf:"varint,8,opt,name=buildingOrUpgradingStartedAt,proto3" json:"buildingOrUpgradingStartedAt,omitempty"`
	ImmediateGoldProductionRate          int32      `protobuf:"varint,9,opt,name=immediateGoldProductionRate,proto3" json:"immediateGoldProductionRate,omitempty"`
	ImmediateRifleProductionRequiredGold int32      `protobuf:"varint,10,opt,name=immediateRifleProductionRequiredGold,proto3" json:"immediateRifleProductionRequiredGold,omitempty"`
	ImmediateRifleProductionDuration     int32      `protobuf:"varint,11,opt,name=immediateRifleProductionDuration,proto3" json:"immediateRifleProductionDuration,omitempty"`
	LastCollectedAt                      uint64     `protobuf:"varint,12,opt,name=lastCollectedAt,proto3" json:"lastCollectedAt,omitempty"`
	XXX_NoUnkeyedLiteral                 struct{}   `json:"-"`
	XXX_unrecognized                     []byte     `json:"-"`
	XXX_sizecache                        int32      `json:"-"`
}

func (m *PlayerBuildableBinding) Reset()         { *m = PlayerBuildableBinding{} }
func (m *PlayerBuildableBinding) String() string { return proto.CompactTextString(m) }
func (*PlayerBuildableBinding) ProtoMessage()    {}
func (*PlayerBuildableBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{4}
}

func (m *PlayerBuildableBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerBuildableBinding.Unmarshal(m, b)
}
func (m *PlayerBuildableBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerBuildableBinding.Marshal(b, m, deterministic)
}
func (m *PlayerBuildableBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerBuildableBinding.Merge(m, src)
}
func (m *PlayerBuildableBinding) XXX_Size() int {
	return xxx_messageInfo_PlayerBuildableBinding.Size(m)
}
func (m *PlayerBuildableBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerBuildableBinding.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerBuildableBinding proto.InternalMessageInfo

func (m *PlayerBuildableBinding) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerBuildableBinding) GetTopmostTileDiscretePositionX() int32 {
	if m != nil {
		return m.TopmostTileDiscretePositionX
	}
	return 0
}

func (m *PlayerBuildableBinding) GetTopmostTileDiscretePositionY() int32 {
	if m != nil {
		return m.TopmostTileDiscretePositionY
	}
	return 0
}

func (m *PlayerBuildableBinding) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *PlayerBuildableBinding) GetBuildable() *Buildable {
	if m != nil {
		return m.Buildable
	}
	return nil
}

func (m *PlayerBuildableBinding) GetCurrentLevel() int32 {
	if m != nil {
		return m.CurrentLevel
	}
	return 0
}

func (m *PlayerBuildableBinding) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *PlayerBuildableBinding) GetBuildingOrUpgradingStartedAt() int64 {
	if m != nil {
		return m.BuildingOrUpgradingStartedAt
	}
	return 0
}

func (m *PlayerBuildableBinding) GetImmediateGoldProductionRate() int32 {
	if m != nil {
		return m.ImmediateGoldProductionRate
	}
	return 0
}

func (m *PlayerBuildableBinding) GetImmediateRifleProductionRequiredGold() int32 {
	if m != nil {
		return m.ImmediateRifleProductionRequiredGold
	}
	return 0
}

func (m *PlayerBuildableBinding) GetImmediateRifleProductionDuration() int32 {
	if m != nil {
		return m.ImmediateRifleProductionDuration
	}
	return 0
}

func (m *PlayerBuildableBinding) GetLastCollectedAt() uint64 {
	if m != nil {
		return m.LastCollectedAt
	}
	return 0
}

type WalletStruct struct {
	Gold                 int32    `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	GoldLimit            int32    `protobuf:"varint,2,opt,name=goldLimit,proto3" json:"goldLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletStruct) Reset()         { *m = WalletStruct{} }
func (m *WalletStruct) String() string { return proto.CompactTextString(m) }
func (*WalletStruct) ProtoMessage()    {}
func (*WalletStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{5}
}

func (m *WalletStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletStruct.Unmarshal(m, b)
}
func (m *WalletStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletStruct.Marshal(b, m, deterministic)
}
func (m *WalletStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletStruct.Merge(m, src)
}
func (m *WalletStruct) XXX_Size() int {
	return xxx_messageInfo_WalletStruct.Size(m)
}
func (m *WalletStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletStruct.DiscardUnknown(m)
}

var xxx_messageInfo_WalletStruct proto.InternalMessageInfo

func (m *WalletStruct) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *WalletStruct) GetGoldLimit() int32 {
	if m != nil {
		return m.GoldLimit
	}
	return 0
}

type LegalCurrencyPaymentRecord struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel              int32    `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	ExtTrxId             string   `protobuf:"bytes,3,opt,name=extTrxId,proto3" json:"extTrxId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LegalCurrencyPaymentRecord) Reset()         { *m = LegalCurrencyPaymentRecord{} }
func (m *LegalCurrencyPaymentRecord) String() string { return proto.CompactTextString(m) }
func (*LegalCurrencyPaymentRecord) ProtoMessage()    {}
func (*LegalCurrencyPaymentRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{6}
}

func (m *LegalCurrencyPaymentRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LegalCurrencyPaymentRecord.Unmarshal(m, b)
}
func (m *LegalCurrencyPaymentRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LegalCurrencyPaymentRecord.Marshal(b, m, deterministic)
}
func (m *LegalCurrencyPaymentRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LegalCurrencyPaymentRecord.Merge(m, src)
}
func (m *LegalCurrencyPaymentRecord) XXX_Size() int {
	return xxx_messageInfo_LegalCurrencyPaymentRecord.Size(m)
}
func (m *LegalCurrencyPaymentRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_LegalCurrencyPaymentRecord.DiscardUnknown(m)
}

var xxx_messageInfo_LegalCurrencyPaymentRecord proto.InternalMessageInfo

func (m *LegalCurrencyPaymentRecord) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LegalCurrencyPaymentRecord) GetChannel() int32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *LegalCurrencyPaymentRecord) GetExtTrxId() string {
	if m != nil {
		return m.ExtTrxId
	}
	return ""
}

type SyncDataStruct struct {
	PlayerBuildableBindingList []*PlayerBuildableBinding `protobuf:"bytes,1,rep,name=playerBuildableBindingList,proto3" json:"playerBuildableBindingList,omitempty"`
	Wallet                     *WalletStruct             `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	TutorialStage              int32                     `protobuf:"varint,3,opt,name=tutorialStage,proto3" json:"tutorialStage,omitempty"`
	QuestCompletedMap          map[int32]int32           `protobuf:"bytes,7,rep,name=questCompletedMap,proto3" json:"questCompletedMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	AccumulatedResource        *AccumulatedResource      `protobuf:"bytes,8,opt,name=accumulatedResource,proto3" json:"accumulatedResource,omitempty"`
	ComboCulmulatedCount       int32                     `protobuf:"varint,9,opt,name=comboCulmulatedCount,proto3" json:"comboCulmulatedCount,omitempty"`
	// use housekeeperLastPeriodStartedAt and housekeeperOfflineIncome temporarily.
	HousekeeperOfflineIncome int32                 `protobuf:"varint,11,opt,name=housekeeperOfflineIncome,proto3" json:"housekeeperOfflineIncome,omitempty"`
	HousekeeperBindingList   []*HousekeeperBinding `protobuf:"bytes,12,rep,name=housekeeperBindingList,proto3" json:"housekeeperBindingList,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}              `json:"-"`
	XXX_unrecognized         []byte                `json:"-"`
	XXX_sizecache            int32                 `json:"-"`
}

func (m *SyncDataStruct) Reset()         { *m = SyncDataStruct{} }
func (m *SyncDataStruct) String() string { return proto.CompactTextString(m) }
func (*SyncDataStruct) ProtoMessage()    {}
func (*SyncDataStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{7}
}

func (m *SyncDataStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncDataStruct.Unmarshal(m, b)
}
func (m *SyncDataStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncDataStruct.Marshal(b, m, deterministic)
}
func (m *SyncDataStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncDataStruct.Merge(m, src)
}
func (m *SyncDataStruct) XXX_Size() int {
	return xxx_messageInfo_SyncDataStruct.Size(m)
}
func (m *SyncDataStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncDataStruct.DiscardUnknown(m)
}

var xxx_messageInfo_SyncDataStruct proto.InternalMessageInfo

func (m *SyncDataStruct) GetPlayerBuildableBindingList() []*PlayerBuildableBinding {
	if m != nil {
		return m.PlayerBuildableBindingList
	}
	return nil
}

func (m *SyncDataStruct) GetWallet() *WalletStruct {
	if m != nil {
		return m.Wallet
	}
	return nil
}

func (m *SyncDataStruct) GetTutorialStage() int32 {
	if m != nil {
		return m.TutorialStage
	}
	return 0
}

func (m *SyncDataStruct) GetQuestCompletedMap() map[int32]int32 {
	if m != nil {
		return m.QuestCompletedMap
	}
	return nil
}

func (m *SyncDataStruct) GetAccumulatedResource() *AccumulatedResource {
	if m != nil {
		return m.AccumulatedResource
	}
	return nil
}

func (m *SyncDataStruct) GetComboCulmulatedCount() int32 {
	if m != nil {
		return m.ComboCulmulatedCount
	}
	return 0
}

func (m *SyncDataStruct) GetHousekeeperOfflineIncome() int32 {
	if m != nil {
		return m.HousekeeperOfflineIncome
	}
	return 0
}

func (m *SyncDataStruct) GetHousekeeperBindingList() []*HousekeeperBinding {
	if m != nil {
		return m.HousekeeperBindingList
	}
	return nil
}

type HousekeeperBinding struct {
	LastPeriodStartedAt  int64    `protobuf:"varint,1,opt,name=lastPeriodStartedAt,proto3" json:"lastPeriodStartedAt,omitempty"`
	BuildableId          int32    `protobuf:"varint,3,opt,name=buildableId,proto3" json:"buildableId,omitempty"`
	CurrentLevel         int32    `protobuf:"varint,4,opt,name=currentLevel,proto3" json:"currentLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HousekeeperBinding) Reset()         { *m = HousekeeperBinding{} }
func (m *HousekeeperBinding) String() string { return proto.CompactTextString(m) }
func (*HousekeeperBinding) ProtoMessage()    {}
func (*HousekeeperBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{8}
}

func (m *HousekeeperBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HousekeeperBinding.Unmarshal(m, b)
}
func (m *HousekeeperBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HousekeeperBinding.Marshal(b, m, deterministic)
}
func (m *HousekeeperBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HousekeeperBinding.Merge(m, src)
}
func (m *HousekeeperBinding) XXX_Size() int {
	return xxx_messageInfo_HousekeeperBinding.Size(m)
}
func (m *HousekeeperBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_HousekeeperBinding.DiscardUnknown(m)
}

var xxx_messageInfo_HousekeeperBinding proto.InternalMessageInfo

func (m *HousekeeperBinding) GetLastPeriodStartedAt() int64 {
	if m != nil {
		return m.LastPeriodStartedAt
	}
	return 0
}

func (m *HousekeeperBinding) GetBuildableId() int32 {
	if m != nil {
		return m.BuildableId
	}
	return 0
}

func (m *HousekeeperBinding) GetCurrentLevel() int32 {
	if m != nil {
		return m.CurrentLevel
	}
	return 0
}

type BuildableLevelConfStruct struct {
	LevelConfList                      []*BuildableLevelBinding          `protobuf:"bytes,1,rep,name=levelConfList,proto3" json:"levelConfList,omitempty"`
	BuildableIngredientInteractionList []*BuildableIngredientInteraction `protobuf:"bytes,2,rep,name=buildableIngredientInteractionList,proto3" json:"buildableIngredientInteractionList,omitempty"`
	XXX_NoUnkeyedLiteral               struct{}                          `json:"-"`
	XXX_unrecognized                   []byte                            `json:"-"`
	XXX_sizecache                      int32                             `json:"-"`
}

func (m *BuildableLevelConfStruct) Reset()         { *m = BuildableLevelConfStruct{} }
func (m *BuildableLevelConfStruct) String() string { return proto.CompactTextString(m) }
func (*BuildableLevelConfStruct) ProtoMessage()    {}
func (*BuildableLevelConfStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{9}
}

func (m *BuildableLevelConfStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildableLevelConfStruct.Unmarshal(m, b)
}
func (m *BuildableLevelConfStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildableLevelConfStruct.Marshal(b, m, deterministic)
}
func (m *BuildableLevelConfStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildableLevelConfStruct.Merge(m, src)
}
func (m *BuildableLevelConfStruct) XXX_Size() int {
	return xxx_messageInfo_BuildableLevelConfStruct.Size(m)
}
func (m *BuildableLevelConfStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildableLevelConfStruct.DiscardUnknown(m)
}

var xxx_messageInfo_BuildableLevelConfStruct proto.InternalMessageInfo

func (m *BuildableLevelConfStruct) GetLevelConfList() []*BuildableLevelBinding {
	if m != nil {
		return m.LevelConfList
	}
	return nil
}

func (m *BuildableLevelConfStruct) GetBuildableIngredientInteractionList() []*BuildableIngredientInteraction {
	if m != nil {
		return m.BuildableIngredientInteractionList
	}
	return nil
}

type Knapsack struct {
	IngredientId         int32    `protobuf:"varint,1,opt,name=ingredientId,proto3" json:"ingredientId,omitempty"`
	CurrentCount         int32    `protobuf:"varint,2,opt,name=currentCount,proto3" json:"currentCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Knapsack) Reset()         { *m = Knapsack{} }
func (m *Knapsack) String() string { return proto.CompactTextString(m) }
func (*Knapsack) ProtoMessage()    {}
func (*Knapsack) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{10}
}

func (m *Knapsack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Knapsack.Unmarshal(m, b)
}
func (m *Knapsack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Knapsack.Marshal(b, m, deterministic)
}
func (m *Knapsack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Knapsack.Merge(m, src)
}
func (m *Knapsack) XXX_Size() int {
	return xxx_messageInfo_Knapsack.Size(m)
}
func (m *Knapsack) XXX_DiscardUnknown() {
	xxx_messageInfo_Knapsack.DiscardUnknown(m)
}

var xxx_messageInfo_Knapsack proto.InternalMessageInfo

func (m *Knapsack) GetIngredientId() int32 {
	if m != nil {
		return m.IngredientId
	}
	return 0
}

func (m *Knapsack) GetCurrentCount() int32 {
	if m != nil {
		return m.CurrentCount
	}
	return 0
}

type RecipeIngredientBinding struct {
	IngredientId               int32    `protobuf:"varint,1,opt,name=ingredientId,proto3" json:"ingredientId,omitempty"`
	Count                      int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	PrependedBinocularOperator string   `protobuf:"bytes,3,opt,name=prependedBinocularOperator,proto3" json:"prependedBinocularOperator,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *RecipeIngredientBinding) Reset()         { *m = RecipeIngredientBinding{} }
func (m *RecipeIngredientBinding) String() string { return proto.CompactTextString(m) }
func (*RecipeIngredientBinding) ProtoMessage()    {}
func (*RecipeIngredientBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{11}
}

func (m *RecipeIngredientBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecipeIngredientBinding.Unmarshal(m, b)
}
func (m *RecipeIngredientBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecipeIngredientBinding.Marshal(b, m, deterministic)
}
func (m *RecipeIngredientBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecipeIngredientBinding.Merge(m, src)
}
func (m *RecipeIngredientBinding) XXX_Size() int {
	return xxx_messageInfo_RecipeIngredientBinding.Size(m)
}
func (m *RecipeIngredientBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_RecipeIngredientBinding.DiscardUnknown(m)
}

var xxx_messageInfo_RecipeIngredientBinding proto.InternalMessageInfo

func (m *RecipeIngredientBinding) GetIngredientId() int32 {
	if m != nil {
		return m.IngredientId
	}
	return 0
}

func (m *RecipeIngredientBinding) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RecipeIngredientBinding) GetPrependedBinocularOperator() string {
	if m != nil {
		return m.PrependedBinocularOperator
	}
	return ""
}

type Ingredient struct {
	Id                           int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                         string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	PriceCurrency                int32    `protobuf:"varint,3,opt,name=PriceCurrency,proto3" json:"PriceCurrency,omitempty"`
	PriceValue                   int32    `protobuf:"varint,4,opt,name=PriceValue,proto3" json:"PriceValue,omitempty"`
	BaseProductionDurationMillis int32    `protobuf:"varint,5,opt,name=BaseProductionDurationMillis,proto3" json:"BaseProductionDurationMillis,omitempty"`
	ReclaimPriceCurrency         int32    `protobuf:"varint,6,opt,name=ReclaimPriceCurrency,proto3" json:"ReclaimPriceCurrency,omitempty"`
	ReclaimPriceValue            int32    `protobuf:"varint,7,opt,name=ReclaimPriceValue,proto3" json:"ReclaimPriceValue,omitempty"`
	BaseReclaimDurationMillis    int32    `protobuf:"varint,8,opt,name=BaseReclaimDurationMillis,proto3" json:"BaseReclaimDurationMillis,omitempty"`
	Category                     int32    `protobuf:"varint,9,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	XXX_unrecognized             []byte   `json:"-"`
	XXX_sizecache                int32    `json:"-"`
}

func (m *Ingredient) Reset()         { *m = Ingredient{} }
func (m *Ingredient) String() string { return proto.CompactTextString(m) }
func (*Ingredient) ProtoMessage()    {}
func (*Ingredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{12}
}

func (m *Ingredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ingredient.Unmarshal(m, b)
}
func (m *Ingredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ingredient.Marshal(b, m, deterministic)
}
func (m *Ingredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingredient.Merge(m, src)
}
func (m *Ingredient) XXX_Size() int {
	return xxx_messageInfo_Ingredient.Size(m)
}
func (m *Ingredient) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingredient.DiscardUnknown(m)
}

var xxx_messageInfo_Ingredient proto.InternalMessageInfo

func (m *Ingredient) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Ingredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ingredient) GetPriceCurrency() int32 {
	if m != nil {
		return m.PriceCurrency
	}
	return 0
}

func (m *Ingredient) GetPriceValue() int32 {
	if m != nil {
		return m.PriceValue
	}
	return 0
}

func (m *Ingredient) GetBaseProductionDurationMillis() int32 {
	if m != nil {
		return m.BaseProductionDurationMillis
	}
	return 0
}

func (m *Ingredient) GetReclaimPriceCurrency() int32 {
	if m != nil {
		return m.ReclaimPriceCurrency
	}
	return 0
}

func (m *Ingredient) GetReclaimPriceValue() int32 {
	if m != nil {
		return m.ReclaimPriceValue
	}
	return 0
}

func (m *Ingredient) GetBaseReclaimDurationMillis() int32 {
	if m != nil {
		return m.BaseReclaimDurationMillis
	}
	return 0
}

func (m *Ingredient) GetCategory() int32 {
	if m != nil {
		return m.Category
	}
	return 0
}

type Recipe struct {
	Id                                 int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetIngredientId                 int32                      `protobuf:"varint,2,opt,name=targetIngredientId,proto3" json:"targetIngredientId,omitempty"`
	TargetIngredientCount              int32                      `protobuf:"varint,3,opt,name=targetIngredientCount,proto3" json:"targetIngredientCount,omitempty"`
	DurationMillis                     int32                      `protobuf:"varint,4,opt,name=durationMillis,proto3" json:"durationMillis,omitempty"`
	ToUnlockSimultaneouslyRecipeIdList string                     `protobuf:"bytes,5,opt,name=toUnlockSimultaneouslyRecipeIdList,proto3" json:"toUnlockSimultaneouslyRecipeIdList,omitempty"`
	RecipeIngredientBindingList        []*RecipeIngredientBinding `protobuf:"bytes,6,rep,name=recipeIngredientBindingList,proto3" json:"recipeIngredientBindingList,omitempty"`
	XXX_NoUnkeyedLiteral               struct{}                   `json:"-"`
	XXX_unrecognized                   []byte                     `json:"-"`
	XXX_sizecache                      int32                      `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{13}
}

func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (m *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(m, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Recipe) GetTargetIngredientId() int32 {
	if m != nil {
		return m.TargetIngredientId
	}
	return 0
}

func (m *Recipe) GetTargetIngredientCount() int32 {
	if m != nil {
		return m.TargetIngredientCount
	}
	return 0
}

func (m *Recipe) GetDurationMillis() int32 {
	if m != nil {
		return m.DurationMillis
	}
	return 0
}

func (m *Recipe) GetToUnlockSimultaneouslyRecipeIdList() string {
	if m != nil {
		return m.ToUnlockSimultaneouslyRecipeIdList
	}
	return ""
}

func (m *Recipe) GetRecipeIngredientBindingList() []*RecipeIngredientBinding {
	if m != nil {
		return m.RecipeIngredientBindingList
	}
	return nil
}

type PlayerRecipe struct {
	RecipeId             int64    `protobuf:"varint,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	State                int32    `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	IngredientId         int64    `protobuf:"varint,3,opt,name=ingredientId,proto3" json:"ingredientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerRecipe) Reset()         { *m = PlayerRecipe{} }
func (m *PlayerRecipe) String() string { return proto.CompactTextString(m) }
func (*PlayerRecipe) ProtoMessage()    {}
func (*PlayerRecipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{14}
}

func (m *PlayerRecipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerRecipe.Unmarshal(m, b)
}
func (m *PlayerRecipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerRecipe.Marshal(b, m, deterministic)
}
func (m *PlayerRecipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerRecipe.Merge(m, src)
}
func (m *PlayerRecipe) XXX_Size() int {
	return xxx_messageInfo_PlayerRecipe.Size(m)
}
func (m *PlayerRecipe) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerRecipe.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerRecipe proto.InternalMessageInfo

func (m *PlayerRecipe) GetRecipeId() int64 {
	if m != nil {
		return m.RecipeId
	}
	return 0
}

func (m *PlayerRecipe) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *PlayerRecipe) GetIngredientId() int64 {
	if m != nil {
		return m.IngredientId
	}
	return 0
}

type StageBuildableLevelDependency struct {
	RequiredBuildableId     int32    `protobuf:"varint,1,opt,name=requiredBuildableId,proto3" json:"requiredBuildableId,omitempty"`
	RequiredBuildableCount  int32    `protobuf:"varint,2,opt,name=requiredBuildableCount,proto3" json:"requiredBuildableCount,omitempty"`
	RequiredMinimumLevel    int32    `protobuf:"varint,3,opt,name=requiredMinimumLevel,proto3" json:"requiredMinimumLevel,omitempty"`
	TargetBuildableMaxCount int32    `protobuf:"varint,4,opt,name=targetBuildableMaxCount,proto3" json:"targetBuildableMaxCount,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *StageBuildableLevelDependency) Reset()         { *m = StageBuildableLevelDependency{} }
func (m *StageBuildableLevelDependency) String() string { return proto.CompactTextString(m) }
func (*StageBuildableLevelDependency) ProtoMessage()    {}
func (*StageBuildableLevelDependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{15}
}

func (m *StageBuildableLevelDependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageBuildableLevelDependency.Unmarshal(m, b)
}
func (m *StageBuildableLevelDependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageBuildableLevelDependency.Marshal(b, m, deterministic)
}
func (m *StageBuildableLevelDependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageBuildableLevelDependency.Merge(m, src)
}
func (m *StageBuildableLevelDependency) XXX_Size() int {
	return xxx_messageInfo_StageBuildableLevelDependency.Size(m)
}
func (m *StageBuildableLevelDependency) XXX_DiscardUnknown() {
	xxx_messageInfo_StageBuildableLevelDependency.DiscardUnknown(m)
}

var xxx_messageInfo_StageBuildableLevelDependency proto.InternalMessageInfo

func (m *StageBuildableLevelDependency) GetRequiredBuildableId() int32 {
	if m != nil {
		return m.RequiredBuildableId
	}
	return 0
}

func (m *StageBuildableLevelDependency) GetRequiredBuildableCount() int32 {
	if m != nil {
		return m.RequiredBuildableCount
	}
	return 0
}

func (m *StageBuildableLevelDependency) GetRequiredMinimumLevel() int32 {
	if m != nil {
		return m.RequiredMinimumLevel
	}
	return 0
}

func (m *StageBuildableLevelDependency) GetTargetBuildableMaxCount() int32 {
	if m != nil {
		return m.TargetBuildableMaxCount
	}
	return 0
}

type StageBuildableLevelBinding struct {
	BuildableId                               int32                            `protobuf:"varint,1,opt,name=buildableId,proto3" json:"buildableId,omitempty"`
	Level                                     int32                            `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	BuildingOrUpgradingDuration               int32                            `protobuf:"varint,3,opt,name=buildingOrUpgradingDuration,proto3" json:"buildingOrUpgradingDuration,omitempty"`
	BuildingOrUpgradingRequiredGold           int32                            `protobuf:"varint,4,opt,name=buildingOrUpgradingRequiredGold,proto3" json:"buildingOrUpgradingRequiredGold,omitempty"`
	BuildingOrUpgradingRequiredResidentsCount int32                            `protobuf:"varint,5,opt,name=buildingOrUpgradingRequiredResidentsCount,proto3" json:"buildingOrUpgradingRequiredResidentsCount,omitempty"`
	BaseGoldProductionRate                    float64                          `protobuf:"fixed64,6,opt,name=baseGoldProductionRate,proto3" json:"baseGoldProductionRate,omitempty"`
	BaseFoodProductionRate                    int32                            `protobuf:"varint,7,opt,name=baseFoodProductionRate,proto3" json:"baseFoodProductionRate,omitempty"`
	BaseRiflemanProductionRequiredGold        int32                            `protobuf:"varint,8,opt,name=baseRiflemanProductionRequiredGold,proto3" json:"baseRiflemanProductionRequiredGold,omitempty"`
	BaseRiflemanProductionDuration            int32                            `protobuf:"varint,9,opt,name=baseRiflemanProductionDuration,proto3" json:"baseRiflemanProductionDuration,omitempty"`
	Dependency                                []*StageBuildableLevelDependency `protobuf:"bytes,10,rep,name=dependency,proto3" json:"dependency,omitempty"`
	GoldLimitAddition                         int32                            `protobuf:"varint,11,opt,name=goldLimitAddition,proto3" json:"goldLimitAddition,omitempty"`
	BaseHp                                    int32                            `protobuf:"varint,12,opt,name=baseHp,proto3" json:"baseHp,omitempty"`
	BaseDamage                                int32                            `protobuf:"varint,13,opt,name=baseDamage,proto3" json:"baseDamage,omitempty"`
	XXX_NoUnkeyedLiteral                      struct{}                         `json:"-"`
	XXX_unrecognized                          []byte                           `json:"-"`
	XXX_sizecache                             int32                            `json:"-"`
}

func (m *StageBuildableLevelBinding) Reset()         { *m = StageBuildableLevelBinding{} }
func (m *StageBuildableLevelBinding) String() string { return proto.CompactTextString(m) }
func (*StageBuildableLevelBinding) ProtoMessage()    {}
func (*StageBuildableLevelBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{16}
}

func (m *StageBuildableLevelBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageBuildableLevelBinding.Unmarshal(m, b)
}
func (m *StageBuildableLevelBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageBuildableLevelBinding.Marshal(b, m, deterministic)
}
func (m *StageBuildableLevelBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageBuildableLevelBinding.Merge(m, src)
}
func (m *StageBuildableLevelBinding) XXX_Size() int {
	return xxx_messageInfo_StageBuildableLevelBinding.Size(m)
}
func (m *StageBuildableLevelBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_StageBuildableLevelBinding.DiscardUnknown(m)
}

var xxx_messageInfo_StageBuildableLevelBinding proto.InternalMessageInfo

func (m *StageBuildableLevelBinding) GetBuildableId() int32 {
	if m != nil {
		return m.BuildableId
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBuildingOrUpgradingDuration() int32 {
	if m != nil {
		return m.BuildingOrUpgradingDuration
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBuildingOrUpgradingRequiredGold() int32 {
	if m != nil {
		return m.BuildingOrUpgradingRequiredGold
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBuildingOrUpgradingRequiredResidentsCount() int32 {
	if m != nil {
		return m.BuildingOrUpgradingRequiredResidentsCount
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBaseGoldProductionRate() float64 {
	if m != nil {
		return m.BaseGoldProductionRate
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBaseFoodProductionRate() int32 {
	if m != nil {
		return m.BaseFoodProductionRate
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBaseRiflemanProductionRequiredGold() int32 {
	if m != nil {
		return m.BaseRiflemanProductionRequiredGold
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBaseRiflemanProductionDuration() int32 {
	if m != nil {
		return m.BaseRiflemanProductionDuration
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetDependency() []*StageBuildableLevelDependency {
	if m != nil {
		return m.Dependency
	}
	return nil
}

func (m *StageBuildableLevelBinding) GetGoldLimitAddition() int32 {
	if m != nil {
		return m.GoldLimitAddition
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBaseHp() int32 {
	if m != nil {
		return m.BaseHp
	}
	return 0
}

func (m *StageBuildableLevelBinding) GetBaseDamage() int32 {
	if m != nil {
		return m.BaseDamage
	}
	return 0
}

type StageGoalQuest struct {
	ResourceType           int32    `protobuf:"varint,1,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	ResourceTargetId       int32    `protobuf:"varint,2,opt,name=resourceTargetId,proto3" json:"resourceTargetId,omitempty"`
	ResourceTargetQuantity int32    `protobuf:"varint,3,opt,name=resourceTargetQuantity,proto3" json:"resourceTargetQuantity,omitempty"`
	CompletedCountRequired int32    `protobuf:"varint,4,opt,name=completedCountRequired,proto3" json:"completedCountRequired,omitempty"`
	ForFailing             int32    `protobuf:"varint,5,opt,name=forFailing,proto3" json:"forFailing,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *StageGoalQuest) Reset()         { *m = StageGoalQuest{} }
func (m *StageGoalQuest) String() string { return proto.CompactTextString(m) }
func (*StageGoalQuest) ProtoMessage()    {}
func (*StageGoalQuest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{17}
}

func (m *StageGoalQuest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageGoalQuest.Unmarshal(m, b)
}
func (m *StageGoalQuest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageGoalQuest.Marshal(b, m, deterministic)
}
func (m *StageGoalQuest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageGoalQuest.Merge(m, src)
}
func (m *StageGoalQuest) XXX_Size() int {
	return xxx_messageInfo_StageGoalQuest.Size(m)
}
func (m *StageGoalQuest) XXX_DiscardUnknown() {
	xxx_messageInfo_StageGoalQuest.DiscardUnknown(m)
}

var xxx_messageInfo_StageGoalQuest proto.InternalMessageInfo

func (m *StageGoalQuest) GetResourceType() int32 {
	if m != nil {
		return m.ResourceType
	}
	return 0
}

func (m *StageGoalQuest) GetResourceTargetId() int32 {
	if m != nil {
		return m.ResourceTargetId
	}
	return 0
}

func (m *StageGoalQuest) GetResourceTargetQuantity() int32 {
	if m != nil {
		return m.ResourceTargetQuantity
	}
	return 0
}

func (m *StageGoalQuest) GetCompletedCountRequired() int32 {
	if m != nil {
		return m.CompletedCountRequired
	}
	return 0
}

func (m *StageGoalQuest) GetForFailing() int32 {
	if m != nil {
		return m.ForFailing
	}
	return 0
}

type StageGoal struct {
	PassScore            int32             `protobuf:"varint,1,opt,name=passScore,proto3" json:"passScore,omitempty"`
	TimeLimitSeconds     int32             `protobuf:"varint,2,opt,name=timeLimitSeconds,proto3" json:"timeLimitSeconds,omitempty"`
	QuestList            []*StageGoalQuest `protobuf:"bytes,3,rep,name=questList,proto3" json:"questList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StageGoal) Reset()         { *m = StageGoal{} }
func (m *StageGoal) String() string { return proto.CompactTextString(m) }
func (*StageGoal) ProtoMessage()    {}
func (*StageGoal) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{18}
}

func (m *StageGoal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageGoal.Unmarshal(m, b)
}
func (m *StageGoal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageGoal.Marshal(b, m, deterministic)
}
func (m *StageGoal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageGoal.Merge(m, src)
}
func (m *StageGoal) XXX_Size() int {
	return xxx_messageInfo_StageGoal.Size(m)
}
func (m *StageGoal) XXX_DiscardUnknown() {
	xxx_messageInfo_StageGoal.DiscardUnknown(m)
}

var xxx_messageInfo_StageGoal proto.InternalMessageInfo

func (m *StageGoal) GetPassScore() int32 {
	if m != nil {
		return m.PassScore
	}
	return 0
}

func (m *StageGoal) GetTimeLimitSeconds() int32 {
	if m != nil {
		return m.TimeLimitSeconds
	}
	return 0
}

func (m *StageGoal) GetQuestList() []*StageGoalQuest {
	if m != nil {
		return m.QuestList
	}
	return nil
}

type AttackWave struct {
	MillisFromStart      int32            `protobuf:"varint,1,opt,name=millisFromStart,proto3" json:"millisFromStart,omitempty"`
	SpeciesCount         map[string]int32 `protobuf:"bytes,2,rep,name=speciesCount,proto3" json:"speciesCount,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AttackWave) Reset()         { *m = AttackWave{} }
func (m *AttackWave) String() string { return proto.CompactTextString(m) }
func (*AttackWave) ProtoMessage()    {}
func (*AttackWave) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{19}
}

func (m *AttackWave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttackWave.Unmarshal(m, b)
}
func (m *AttackWave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttackWave.Marshal(b, m, deterministic)
}
func (m *AttackWave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttackWave.Merge(m, src)
}
func (m *AttackWave) XXX_Size() int {
	return xxx_messageInfo_AttackWave.Size(m)
}
func (m *AttackWave) XXX_DiscardUnknown() {
	xxx_messageInfo_AttackWave.DiscardUnknown(m)
}

var xxx_messageInfo_AttackWave proto.InternalMessageInfo

func (m *AttackWave) GetMillisFromStart() int32 {
	if m != nil {
		return m.MillisFromStart
	}
	return 0
}

func (m *AttackWave) GetSpeciesCount() map[string]int32 {
	if m != nil {
		return m.SpeciesCount
	}
	return nil
}

type GuardSoldier struct {
	Species               string   `protobuf:"bytes,1,opt,name=species,proto3" json:"species,omitempty"`
	TileDiscretePositionX int32    `protobuf:"varint,2,opt,name=tileDiscretePositionX,proto3" json:"tileDiscretePositionX,omitempty"`
	TileDiscretePositionY int32    `protobuf:"varint,3,opt,name=tileDiscretePositionY,proto3" json:"tileDiscretePositionY,omitempty"`
	TeamId                int32    `protobuf:"varint,4,opt,name=teamId,proto3" json:"teamId,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *GuardSoldier) Reset()         { *m = GuardSoldier{} }
func (m *GuardSoldier) String() string { return proto.CompactTextString(m) }
func (*GuardSoldier) ProtoMessage()    {}
func (*GuardSoldier) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{20}
}

func (m *GuardSoldier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuardSoldier.Unmarshal(m, b)
}
func (m *GuardSoldier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuardSoldier.Marshal(b, m, deterministic)
}
func (m *GuardSoldier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuardSoldier.Merge(m, src)
}
func (m *GuardSoldier) XXX_Size() int {
	return xxx_messageInfo_GuardSoldier.Size(m)
}
func (m *GuardSoldier) XXX_DiscardUnknown() {
	xxx_messageInfo_GuardSoldier.DiscardUnknown(m)
}

var xxx_messageInfo_GuardSoldier proto.InternalMessageInfo

func (m *GuardSoldier) GetSpecies() string {
	if m != nil {
		return m.Species
	}
	return ""
}

func (m *GuardSoldier) GetTileDiscretePositionX() int32 {
	if m != nil {
		return m.TileDiscretePositionX
	}
	return 0
}

func (m *GuardSoldier) GetTileDiscretePositionY() int32 {
	if m != nil {
		return m.TileDiscretePositionY
	}
	return 0
}

func (m *GuardSoldier) GetTeamId() int32 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

type StageInitialState struct {
	StageId                        int32                         `protobuf:"varint,1,opt,name=stageId,proto3" json:"stageId,omitempty"`
	Knapsack                       []*Knapsack                   `protobuf:"bytes,2,rep,name=knapsack,proto3" json:"knapsack,omitempty"`
	PlayerRecipeList               []*PlayerRecipe               `protobuf:"bytes,3,rep,name=playerRecipeList,proto3" json:"playerRecipeList,omitempty"`
	StageBuildableLevelBindingList []*StageBuildableLevelBinding `protobuf:"bytes,4,rep,name=stageBuildableLevelBindingList,proto3" json:"stageBuildableLevelBindingList,omitempty"`
	SyncData                       *SyncDataStruct               `protobuf:"bytes,5,opt,name=syncData,proto3" json:"syncData,omitempty"`
	Goal                           *StageGoal                    `protobuf:"bytes,6,opt,name=goal,proto3" json:"goal,omitempty"`
	DiamondPrice                   int32                         `protobuf:"varint,7,opt,name=diamondPrice,proto3" json:"diamondPrice,omitempty"`
	StarPrice                      int32                         `protobuf:"varint,8,opt,name=starPrice,proto3" json:"starPrice,omitempty"`
	AttackWaveList                 []*AttackWave                 `protobuf:"bytes,9,rep,name=attackWaveList,proto3" json:"attackWaveList,omitempty"`
	GuardSoldierList               []*GuardSoldier               `protobuf:"bytes,10,rep,name=guardSoldierList,proto3" json:"guardSoldierList,omitempty"`
	TicketPrice                    int32                         `protobuf:"varint,11,opt,name=ticketPrice,proto3" json:"ticketPrice,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                      `json:"-"`
	XXX_unrecognized               []byte                        `json:"-"`
	XXX_sizecache                  int32                         `json:"-"`
}

func (m *StageInitialState) Reset()         { *m = StageInitialState{} }
func (m *StageInitialState) String() string { return proto.CompactTextString(m) }
func (*StageInitialState) ProtoMessage()    {}
func (*StageInitialState) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{21}
}

func (m *StageInitialState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageInitialState.Unmarshal(m, b)
}
func (m *StageInitialState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageInitialState.Marshal(b, m, deterministic)
}
func (m *StageInitialState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageInitialState.Merge(m, src)
}
func (m *StageInitialState) XXX_Size() int {
	return xxx_messageInfo_StageInitialState.Size(m)
}
func (m *StageInitialState) XXX_DiscardUnknown() {
	xxx_messageInfo_StageInitialState.DiscardUnknown(m)
}

var xxx_messageInfo_StageInitialState proto.InternalMessageInfo

func (m *StageInitialState) GetStageId() int32 {
	if m != nil {
		return m.StageId
	}
	return 0
}

func (m *StageInitialState) GetKnapsack() []*Knapsack {
	if m != nil {
		return m.Knapsack
	}
	return nil
}

func (m *StageInitialState) GetPlayerRecipeList() []*PlayerRecipe {
	if m != nil {
		return m.PlayerRecipeList
	}
	return nil
}

func (m *StageInitialState) GetStageBuildableLevelBindingList() []*StageBuildableLevelBinding {
	if m != nil {
		return m.StageBuildableLevelBindingList
	}
	return nil
}

func (m *StageInitialState) GetSyncData() *SyncDataStruct {
	if m != nil {
		return m.SyncData
	}
	return nil
}

func (m *StageInitialState) GetGoal() *StageGoal {
	if m != nil {
		return m.Goal
	}
	return nil
}

func (m *StageInitialState) GetDiamondPrice() int32 {
	if m != nil {
		return m.DiamondPrice
	}
	return 0
}

func (m *StageInitialState) GetStarPrice() int32 {
	if m != nil {
		return m.StarPrice
	}
	return 0
}

func (m *StageInitialState) GetAttackWaveList() []*AttackWave {
	if m != nil {
		return m.AttackWaveList
	}
	return nil
}

func (m *StageInitialState) GetGuardSoldierList() []*GuardSoldier {
	if m != nil {
		return m.GuardSoldierList
	}
	return nil
}

func (m *StageInitialState) GetTicketPrice() int32 {
	if m != nil {
		return m.TicketPrice
	}
	return 0
}

type GraphSuccessorList struct {
	ListContent          []int32  `protobuf:"varint,1,rep,packed,name=listContent,proto3" json:"listContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GraphSuccessorList) Reset()         { *m = GraphSuccessorList{} }
func (m *GraphSuccessorList) String() string { return proto.CompactTextString(m) }
func (*GraphSuccessorList) ProtoMessage()    {}
func (*GraphSuccessorList) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{22}
}

func (m *GraphSuccessorList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphSuccessorList.Unmarshal(m, b)
}
func (m *GraphSuccessorList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphSuccessorList.Marshal(b, m, deterministic)
}
func (m *GraphSuccessorList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphSuccessorList.Merge(m, src)
}
func (m *GraphSuccessorList) XXX_Size() int {
	return xxx_messageInfo_GraphSuccessorList.Size(m)
}
func (m *GraphSuccessorList) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphSuccessorList.DiscardUnknown(m)
}

var xxx_messageInfo_GraphSuccessorList proto.InternalMessageInfo

func (m *GraphSuccessorList) GetListContent() []int32 {
	if m != nil {
		return m.ListContent
	}
	return nil
}

type GraphSuccessorListDict struct {
	DictContent          map[int32]*GraphSuccessorList `protobuf:"bytes,1,rep,name=dictContent,proto3" json:"dictContent,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GraphSuccessorListDict) Reset()         { *m = GraphSuccessorListDict{} }
func (m *GraphSuccessorListDict) String() string { return proto.CompactTextString(m) }
func (*GraphSuccessorListDict) ProtoMessage()    {}
func (*GraphSuccessorListDict) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{23}
}

func (m *GraphSuccessorListDict) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GraphSuccessorListDict.Unmarshal(m, b)
}
func (m *GraphSuccessorListDict) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GraphSuccessorListDict.Marshal(b, m, deterministic)
}
func (m *GraphSuccessorListDict) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GraphSuccessorListDict.Merge(m, src)
}
func (m *GraphSuccessorListDict) XXX_Size() int {
	return xxx_messageInfo_GraphSuccessorListDict.Size(m)
}
func (m *GraphSuccessorListDict) XXX_DiscardUnknown() {
	xxx_messageInfo_GraphSuccessorListDict.DiscardUnknown(m)
}

var xxx_messageInfo_GraphSuccessorListDict proto.InternalMessageInfo

func (m *GraphSuccessorListDict) GetDictContent() map[int32]*GraphSuccessorList {
	if m != nil {
		return m.DictContent
	}
	return nil
}

type InterruptTutorialMask struct {
	VisitedGroups        map[int32]*GraphSuccessorListDict `protobuf:"bytes,1,rep,name=visitedGroups,proto3" json:"visitedGroups,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *InterruptTutorialMask) Reset()         { *m = InterruptTutorialMask{} }
func (m *InterruptTutorialMask) String() string { return proto.CompactTextString(m) }
func (*InterruptTutorialMask) ProtoMessage()    {}
func (*InterruptTutorialMask) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{24}
}

func (m *InterruptTutorialMask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterruptTutorialMask.Unmarshal(m, b)
}
func (m *InterruptTutorialMask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterruptTutorialMask.Marshal(b, m, deterministic)
}
func (m *InterruptTutorialMask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterruptTutorialMask.Merge(m, src)
}
func (m *InterruptTutorialMask) XXX_Size() int {
	return xxx_messageInfo_InterruptTutorialMask.Size(m)
}
func (m *InterruptTutorialMask) XXX_DiscardUnknown() {
	xxx_messageInfo_InterruptTutorialMask.DiscardUnknown(m)
}

var xxx_messageInfo_InterruptTutorialMask proto.InternalMessageInfo

func (m *InterruptTutorialMask) GetVisitedGroups() map[int32]*GraphSuccessorListDict {
	if m != nil {
		return m.VisitedGroups
	}
	return nil
}

type AccumulatedResource struct {
	ServedCustomer       int32           `protobuf:"varint,5,opt,name=servedCustomer,proto3" json:"servedCustomer,omitempty"`
	DishSold             int32           `protobuf:"varint,6,opt,name=dishSold,proto3" json:"dishSold,omitempty"`
	IngredientProduced   map[int32]int32 `protobuf:"bytes,7,rep,name=ingredientProduced,proto3" json:"ingredientProduced,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	FreeOrderIncome      int32           `protobuf:"varint,8,opt,name=freeOrderIncome,proto3" json:"freeOrderIncome,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AccumulatedResource) Reset()         { *m = AccumulatedResource{} }
func (m *AccumulatedResource) String() string { return proto.CompactTextString(m) }
func (*AccumulatedResource) ProtoMessage()    {}
func (*AccumulatedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_05be4a6a62f41c0d, []int{25}
}

func (m *AccumulatedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccumulatedResource.Unmarshal(m, b)
}
func (m *AccumulatedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccumulatedResource.Marshal(b, m, deterministic)
}
func (m *AccumulatedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccumulatedResource.Merge(m, src)
}
func (m *AccumulatedResource) XXX_Size() int {
	return xxx_messageInfo_AccumulatedResource.Size(m)
}
func (m *AccumulatedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AccumulatedResource.DiscardUnknown(m)
}

var xxx_messageInfo_AccumulatedResource proto.InternalMessageInfo

func (m *AccumulatedResource) GetServedCustomer() int32 {
	if m != nil {
		return m.ServedCustomer
	}
	return 0
}

func (m *AccumulatedResource) GetDishSold() int32 {
	if m != nil {
		return m.DishSold
	}
	return 0
}

func (m *AccumulatedResource) GetIngredientProduced() map[int32]int32 {
	if m != nil {
		return m.IngredientProduced
	}
	return nil
}

func (m *AccumulatedResource) GetFreeOrderIncome() int32 {
	if m != nil {
		return m.FreeOrderIncome
	}
	return 0
}

func init() {
	proto.RegisterType((*Buildable)(nil), "mineralchem.Buildable")
	proto.RegisterType((*BuildableLevelBinding)(nil), "mineralchem.BuildableLevelBinding")
	proto.RegisterType((*BuildableLevelDependency)(nil), "mineralchem.BuildableLevelDependency")
	proto.RegisterType((*BuildableIngredientInteraction)(nil), "mineralchem.BuildableIngredientInteraction")
	proto.RegisterType((*PlayerBuildableBinding)(nil), "mineralchem.PlayerBuildableBinding")
	proto.RegisterType((*WalletStruct)(nil), "mineralchem.WalletStruct")
	proto.RegisterType((*LegalCurrencyPaymentRecord)(nil), "mineralchem.LegalCurrencyPaymentRecord")
	proto.RegisterType((*SyncDataStruct)(nil), "mineralchem.SyncDataStruct")
	proto.RegisterMapType((map[int32]int32)(nil), "mineralchem.SyncDataStruct.QuestCompletedMapEntry")
	proto.RegisterType((*HousekeeperBinding)(nil), "mineralchem.HousekeeperBinding")
	proto.RegisterType((*BuildableLevelConfStruct)(nil), "mineralchem.BuildableLevelConfStruct")
	proto.RegisterType((*Knapsack)(nil), "mineralchem.Knapsack")
	proto.RegisterType((*RecipeIngredientBinding)(nil), "mineralchem.RecipeIngredientBinding")
	proto.RegisterType((*Ingredient)(nil), "mineralchem.Ingredient")
	proto.RegisterType((*Recipe)(nil), "mineralchem.Recipe")
	proto.RegisterType((*PlayerRecipe)(nil), "mineralchem.PlayerRecipe")
	proto.RegisterType((*StageBuildableLevelDependency)(nil), "mineralchem.StageBuildableLevelDependency")
	proto.RegisterType((*StageBuildableLevelBinding)(nil), "mineralchem.StageBuildableLevelBinding")
	proto.RegisterType((*StageGoalQuest)(nil), "mineralchem.StageGoalQuest")
	proto.RegisterType((*StageGoal)(nil), "mineralchem.StageGoal")
	proto.RegisterType((*AttackWave)(nil), "mineralchem.AttackWave")
	proto.RegisterMapType((map[string]int32)(nil), "mineralchem.AttackWave.SpeciesCountEntry")
	proto.RegisterType((*GuardSoldier)(nil), "mineralchem.GuardSoldier")
	proto.RegisterType((*StageInitialState)(nil), "mineralchem.StageInitialState")
	proto.RegisterType((*GraphSuccessorList)(nil), "mineralchem.GraphSuccessorList")
	proto.RegisterType((*GraphSuccessorListDict)(nil), "mineralchem.GraphSuccessorListDict")
	proto.RegisterMapType((map[int32]*GraphSuccessorList)(nil), "mineralchem.GraphSuccessorListDict.DictContentEntry")
	proto.RegisterType((*InterruptTutorialMask)(nil), "mineralchem.InterruptTutorialMask")
	proto.RegisterMapType((map[int32]*GraphSuccessorListDict)(nil), "mineralchem.InterruptTutorialMask.VisitedGroupsEntry")
	proto.RegisterType((*AccumulatedResource)(nil), "mineralchem.AccumulatedResource")
	proto.RegisterMapType((map[int32]int32)(nil), "mineralchem.AccumulatedResource.IngredientProducedEntry")
}

func init() { proto.RegisterFile("Buildable.proto", fileDescriptor_05be4a6a62f41c0d) }

var fileDescriptor_05be4a6a62f41c0d = []byte{
	// 2223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x59, 0x4f, 0x73, 0x1c, 0x47,
	0x15, 0xaf, 0x59, 0x69, 0x65, 0xed, 0x5b, 0x59, 0xb1, 0xdb, 0xb6, 0xbc, 0x5e, 0x1b, 0x45, 0x4c,
	0x0c, 0x28, 0x86, 0x52, 0x11, 0xe1, 0x04, 0x27, 0x45, 0x91, 0x58, 0x92, 0x2d, 0x29, 0x48, 0xb6,
	0x32, 0xab, 0xd8, 0xa4, 0xa0, 0x0a, 0x5a, 0x33, 0xad, 0x55, 0x97, 0x66, 0xa6, 0x27, 0x3d, 0x3d,
	0xc2, 0x5b, 0xdc, 0x38, 0xe7, 0x40, 0x91, 0xaf, 0xc1, 0x91, 0x2f, 0xc0, 0x85, 0x3b, 0x67, 0xaa,
	0xa8, 0xe2, 0xc8, 0x8d, 0xe2, 0x00, 0x1c, 0xa9, 0xfe, 0x33, 0xb3, 0x3d, 0x3b, 0x33, 0xbb, 0x0a,
	0x65, 0x4e, 0xb9, 0x6d, 0xbf, 0xf7, 0xfa, 0xcd, 0xeb, 0xd7, 0xef, 0xfd, 0xde, 0xeb, 0xb7, 0xf0,
	0xc6, 0x56, 0x46, 0xc3, 0x00, 0x9f, 0x84, 0x64, 0x23, 0xe1, 0x4c, 0x30, 0xd4, 0x8d, 0x68, 0x4c,
	0x38, 0x0e, 0xfd, 0x33, 0x12, 0xb9, 0x7f, 0x74, 0xa0, 0x53, 0x08, 0xa0, 0x65, 0x68, 0xd1, 0xa0,
	0xe7, 0xac, 0x39, 0xeb, 0x6d, 0xaf, 0x45, 0x03, 0x84, 0x60, 0x5e, 0x8c, 0x12, 0xd2, 0x6b, 0x29,
	0x8a, 0xfa, 0x8d, 0xee, 0xc3, 0xd5, 0x80, 0xa6, 0x3e, 0x27, 0x82, 0xbc, 0xa4, 0x81, 0x38, 0xeb,
	0xcd, 0x29, 0x66, 0x99, 0x88, 0xbe, 0x0d, 0xcb, 0x39, 0x61, 0x8f, 0xd0, 0xe1, 0x99, 0xe8, 0xcd,
	0x2b, 0xb1, 0x09, 0x2a, 0x5a, 0x83, 0x6e, 0x40, 0xd3, 0x24, 0xc4, 0xa3, 0x67, 0x38, 0x22, 0xbd,
	0xf6, 0x9a, 0xb3, 0xde, 0xf1, 0x6c, 0x92, 0x94, 0xc0, 0x99, 0x60, 0xdb, 0x2c, 0x0c, 0x89, 0x2f,
	0x7a, 0x0b, 0x4a, 0x8d, 0x4d, 0x72, 0x7f, 0xb7, 0x00, 0xb7, 0x8a, 0x33, 0x1c, 0x90, 0x0b, 0x12,
	0x6e, 0xd1, 0x38, 0xa0, 0xf1, 0xb0, 0x72, 0x9e, 0x87, 0xd0, 0x39, 0xc9, 0x05, 0xd5, 0xa1, 0xba,
	0x9b, 0x2b, 0x1b, 0x96, 0x3b, 0x36, 0x0a, 0x35, 0xde, 0x58, 0x10, 0xdd, 0x84, 0x76, 0x28, 0xb5,
	0x9a, 0x93, 0xea, 0x05, 0xfa, 0x08, 0xee, 0x2a, 0x11, 0x1a, 0x0f, 0x9f, 0xf3, 0x4f, 0x93, 0x21,
	0xc7, 0xf2, 0xe7, 0x4e, 0xc6, 0xb1, 0xa0, 0x2c, 0x36, 0xc7, 0x9d, 0x26, 0x82, 0xf6, 0xe0, 0xcd,
	0x1a, 0xb6, 0x47, 0x3e, 0xcf, 0x28, 0x27, 0xc1, 0x2e, 0x0b, 0x03, 0xe5, 0x8f, 0xb6, 0x37, 0x4b,
	0x0c, 0xfd, 0x1c, 0xde, 0x9e, 0x22, 0xe2, 0x91, 0x94, 0x06, 0x24, 0x16, 0xe9, 0x36, 0xcb, 0xe2,
	0xdc, 0x83, 0x97, 0xdf, 0x80, 0xde, 0x83, 0x95, 0x13, 0x9c, 0x12, 0xf9, 0xa5, 0x23, 0xce, 0x82,
	0xcc, 0x97, 0xd6, 0x7b, 0x58, 0x90, 0xde, 0x95, 0x35, 0x67, 0xdd, 0xf1, 0x1a, 0xb8, 0xf9, 0xbe,
	0xa7, 0x8c, 0x4d, 0xee, 0x5b, 0x54, 0x26, 0x34, 0x70, 0xd1, 0x33, 0x70, 0x25, 0xc7, 0xa3, 0xa7,
	0x21, 0x89, 0x70, 0x6c, 0x71, 0x6d, 0xd7, 0x74, 0x94, 0x8e, 0x4b, 0x48, 0xa2, 0xa7, 0xb0, 0x5a,
	0x2f, 0x55, 0x5c, 0x16, 0x28, 0x5d, 0x33, 0xa4, 0xd0, 0x13, 0x80, 0x80, 0x24, 0x24, 0x0e, 0x48,
	0xec, 0x8f, 0x7a, 0xdd, 0xb5, 0xb9, 0xf5, 0xee, 0xe6, 0xb7, 0xea, 0xc3, 0x47, 0x45, 0xe1, 0x4e,
	0x21, 0xec, 0x59, 0x1b, 0xd1, 0xf7, 0xe0, 0xfa, 0x90, 0x85, 0xc1, 0x01, 0x8d, 0xa8, 0x78, 0x1c,
	0x04, 0x54, 0x59, 0xb0, 0xa4, 0x2c, 0xa8, 0x32, 0xd0, 0x0a, 0x2c, 0x48, 0xb3, 0xf6, 0x92, 0xde,
	0x55, 0x25, 0x62, 0x56, 0x68, 0x15, 0x40, 0xfe, 0xda, 0xc1, 0x11, 0x1e, 0x92, 0xde, 0xb2, 0xe2,
	0x59, 0x14, 0xf7, 0x9f, 0x0e, 0xf4, 0x9a, 0xcc, 0x41, 0xdf, 0x87, 0x1b, 0xdc, 0x78, 0xa8, 0x90,
	0xd9, 0xcf, 0x13, 0xa5, 0x8e, 0x25, 0xef, 0xb2, 0x42, 0xd6, 0xe1, 0xa4, 0xb1, 0xa1, 0x81, 0x8b,
	0x36, 0xe1, 0x66, 0xce, 0x39, 0xa4, 0x31, 0x8d, 0xb2, 0xe8, 0xc0, 0x4a, 0xa5, 0x5a, 0x1e, 0x7a,
	0x04, 0xb7, 0x05, 0xe6, 0x43, 0x22, 0x0a, 0x5d, 0x87, 0xf8, 0x95, 0xfe, 0x98, 0xce, 0xaa, 0x26,
	0xb6, 0xfb, 0x9b, 0x39, 0x58, 0x1d, 0x5b, 0x1d, 0x0f, 0x39, 0x09, 0x28, 0x89, 0xc5, 0x7e, 0x2c,
	0x08, 0xc7, 0xea, 0x32, 0x2b, 0x90, 0xb0, 0x06, 0xdd, 0x13, 0xcb, 0x05, 0xfa, 0x34, 0x36, 0x09,
	0xb9, 0xb0, 0x44, 0xc7, 0xaa, 0x02, 0x63, 0x7a, 0x89, 0x56, 0x00, 0xe5, 0xbc, 0x05, 0x94, 0x07,
	0xf0, 0xcd, 0x93, 0xd2, 0x05, 0x1c, 0xb3, 0x4f, 0xe3, 0x90, 0xf9, 0xe7, 0x3b, 0x13, 0x80, 0xd7,
	0xf6, 0x66, 0x0b, 0xa2, 0x3e, 0x2c, 0x72, 0xe2, 0xd3, 0x44, 0x1a, 0xa9, 0x33, 0xb8, 0x58, 0x4b,
	0x20, 0x19, 0x5b, 0x73, 0x94, 0x71, 0xff, 0x0c, 0xa7, 0xe4, 0x88, 0x53, 0x9f, 0x6c, 0x67, 0x9c,
	0xab, 0x68, 0xbd, 0xa2, 0x81, 0x64, 0x86, 0x18, 0xda, 0x82, 0x7b, 0x0d, 0x22, 0x2f, 0x70, 0x98,
	0xe5, 0x89, 0x3b, 0x55, 0xc6, 0xfd, 0xa2, 0x0d, 0x2b, 0x47, 0x21, 0x1e, 0x11, 0x5e, 0x5c, 0x45,
	0x13, 0x1e, 0x6f, 0xc1, 0x3d, 0xc1, 0x92, 0x88, 0xa5, 0xe2, 0x98, 0x86, 0x64, 0xc7, 0x94, 0x86,
	0x23, 0x96, 0xaa, 0xd8, 0xff, 0xa9, 0xb9, 0x8d, 0xa9, 0x32, 0x33, 0x74, 0x7c, 0x66, 0xae, 0x6b,
	0xaa, 0x8c, 0x74, 0x6e, 0xa2, 0x2c, 0xde, 0x0f, 0xcc, 0x15, 0x16, 0xeb, 0x72, 0xcd, 0x68, 0x5f,
	0xb6, 0x66, 0xb8, 0xb0, 0xe4, 0x2b, 0xa7, 0x0a, 0x1d, 0xef, 0xfa, 0xca, 0x4a, 0x34, 0x59, 0x57,
	0x52, 0x91, 0xc3, 0x68, 0xdb, 0xd3, 0x0b, 0x79, 0x9e, 0x1a, 0x68, 0x1e, 0x08, 0xcc, 0x05, 0x09,
	0x1e, 0x0b, 0x75, 0x05, 0x73, 0xde, 0x54, 0x19, 0x59, 0x9b, 0x68, 0x14, 0x91, 0x80, 0x62, 0x51,
	0x07, 0xdb, 0x1a, 0x3a, 0xa7, 0x89, 0x20, 0x0f, 0xee, 0x17, 0x6c, 0x05, 0x89, 0x0d, 0x28, 0xac,
	0x91, 0xf3, 0x52, 0xb2, 0xe8, 0x63, 0x58, 0x6b, 0x92, 0x2b, 0x90, 0xb8, 0xab, 0xf4, 0xcd, 0x94,
	0x43, 0xeb, 0xf0, 0x46, 0x88, 0x53, 0x61, 0x5a, 0x00, 0xe5, 0x18, 0x09, 0xa1, 0xf3, 0xde, 0x24,
	0xd9, 0xfd, 0x08, 0x96, 0x5e, 0xe2, 0x30, 0x24, 0x62, 0x20, 0x78, 0xe6, 0x0b, 0x99, 0xaa, 0x12,
	0x65, 0x4d, 0x14, 0xaa, 0xdf, 0xe8, 0x1e, 0x74, 0x0a, 0xe4, 0x35, 0x41, 0x37, 0x26, 0xb8, 0x27,
	0xd0, 0x3f, 0x20, 0x43, 0x1c, 0xe6, 0x59, 0x72, 0x84, 0x47, 0x11, 0x89, 0x85, 0x47, 0x7c, 0xc6,
	0x83, 0x4a, 0x4c, 0xf7, 0xe0, 0x8a, 0x7f, 0x86, 0xe3, 0x98, 0x84, 0x46, 0x53, 0xbe, 0x94, 0x51,
	0x46, 0x5e, 0x89, 0x63, 0xfe, 0xca, 0x80, 0x48, 0xc7, 0x2b, 0xd6, 0xee, 0x97, 0x6d, 0x58, 0x1e,
	0x8c, 0x62, 0x7f, 0x07, 0x0b, 0x6c, 0x0c, 0xf5, 0xa1, 0x9f, 0xd4, 0xa6, 0xd1, 0x01, 0x4d, 0x45,
	0xcf, 0x51, 0xe5, 0xe7, 0xad, 0x52, 0x24, 0xd6, 0x67, 0x9d, 0x37, 0x45, 0x0d, 0x7a, 0x07, 0x16,
	0x7e, 0xa5, 0xbc, 0x63, 0xda, 0xa1, 0x3b, 0x25, 0x85, 0xb6, 0xe3, 0x3c, 0x23, 0x28, 0x1b, 0x40,
	0x91, 0x09, 0xc6, 0x29, 0x0e, 0x07, 0x42, 0x16, 0x1f, 0xd3, 0x00, 0x96, 0x88, 0xe8, 0x97, 0x70,
	0xfd, 0xf3, 0x8c, 0xc8, 0xab, 0x88, 0x92, 0x90, 0x08, 0x12, 0x1c, 0xe2, 0xa4, 0x77, 0x45, 0x19,
	0xbd, 0x59, 0xfa, 0x46, 0xf9, 0xd4, 0x1b, 0x9f, 0x4c, 0x6e, 0x7a, 0x12, 0x0b, 0x3e, 0xf2, 0xaa,
	0xca, 0x90, 0x07, 0x37, 0xb0, 0xef, 0x67, 0x51, 0x16, 0x62, 0xa1, 0x7a, 0x16, 0x96, 0x71, 0x5f,
	0x43, 0x54, 0x77, 0x73, 0xad, 0xf4, 0x8d, 0xc7, 0x55, 0x39, 0xaf, 0x6e, 0xb3, 0x2c, 0x57, 0x3e,
	0x8b, 0x4e, 0xd8, 0x76, 0x16, 0x1a, 0x96, 0xae, 0x3b, 0x3a, 0x63, 0x6a, 0x79, 0xe8, 0x03, 0xe8,
	0x9d, 0xb1, 0x2c, 0x25, 0xe7, 0x84, 0x24, 0x84, 0x3f, 0x3f, 0x3d, 0x0d, 0x69, 0x4c, 0xf6, 0x63,
	0x9f, 0x45, 0xc4, 0x84, 0x73, 0x23, 0x1f, 0xbd, 0x84, 0x15, 0x8b, 0x67, 0xdf, 0xef, 0x92, 0x72,
	0xd5, 0x9b, 0xa5, 0x63, 0xec, 0x55, 0x44, 0xbd, 0x86, 0xed, 0xfd, 0x1d, 0x58, 0xa9, 0xf7, 0x24,
	0xba, 0x06, 0x73, 0xe7, 0x64, 0x64, 0x02, 0x56, 0xfe, 0x94, 0x38, 0x74, 0xa1, 0xd0, 0x5d, 0xc7,
	0xab, 0x5e, 0x7c, 0xd0, 0x7a, 0xe4, 0xb8, 0x5f, 0x38, 0x80, 0xaa, 0x1f, 0x95, 0xed, 0x83, 0xcc,
	0xb2, 0x23, 0xc2, 0x29, 0x0b, 0xc6, 0xc8, 0xe4, 0x28, 0x64, 0xaa, 0x63, 0x4d, 0x56, 0xd9, 0xb9,
	0xda, 0x2a, 0x5b, 0x02, 0xcc, 0xf9, 0x2a, 0x60, 0xba, 0x7f, 0xab, 0xf4, 0x34, 0xdb, 0x2c, 0x3e,
	0x35, 0xe9, 0xb2, 0x07, 0x57, 0xc3, 0x9c, 0x64, 0x65, 0x88, 0x3b, 0xa5, 0x41, 0xcb, 0x9d, 0x58,
	0xde, 0x88, 0x7e, 0x0d, 0xee, 0xc9, 0xd4, 0x26, 0x42, 0xa9, 0x6f, 0x29, 0xf5, 0xdf, 0xad, 0x57,
	0x5f, 0xbb, 0xcd, 0xbb, 0x84, 0x5a, 0xd7, 0x83, 0xc5, 0x9f, 0xc4, 0x38, 0x49, 0xb1, 0x7f, 0x5e,
	0xe9, 0x3c, 0x9c, 0x9a, 0xce, 0x63, 0xec, 0x37, 0xbb, 0x1d, 0x2b, 0xd1, 0xdc, 0x2f, 0x1d, 0xb8,
	0xed, 0xe9, 0x66, 0xa1, 0xd8, 0x9a, 0xdf, 0xe5, 0x65, 0xbe, 0x71, 0x13, 0xda, 0xbe, 0xa5, 0x5c,
	0x2f, 0xd0, 0x8f, 0xa1, 0x9f, 0x70, 0xdd, 0x53, 0x06, 0x5b, 0x34, 0x66, 0x7e, 0x16, 0x62, 0xfe,
	0x3c, 0x21, 0x1c, 0x0b, 0xc6, 0x0d, 0xc0, 0x4d, 0x91, 0x70, 0xff, 0xd5, 0x02, 0x18, 0xdb, 0x23,
	0x71, 0xb4, 0xf8, 0x7c, 0x4b, 0xb7, 0x54, 0xaa, 0x43, 0x6a, 0x29, 0x45, 0xea, 0xb7, 0x84, 0x9e,
	0x72, 0x5b, 0x63, 0xa0, 0xa7, 0xdc, 0xc4, 0xac, 0x02, 0x58, 0x2d, 0x8b, 0x0e, 0x24, 0x8b, 0x22,
	0x2b, 0xec, 0x96, 0x6a, 0x59, 0x26, 0xab, 0xca, 0x21, 0x0d, 0x43, 0x9a, 0x9a, 0x9e, 0x6c, 0xaa,
	0x8c, 0x04, 0x0a, 0x8f, 0xf8, 0x21, 0xa6, 0x51, 0xd9, 0x20, 0x5d, 0xe7, 0x6b, 0x79, 0xb2, 0xf1,
	0xb7, 0xe9, 0xda, 0x3c, 0x5d, 0xfb, 0xab, 0x0c, 0xf4, 0x23, 0xb8, 0x23, 0x2d, 0x30, 0x8c, 0x09,
	0x13, 0x75, 0x1f, 0xd6, 0x2c, 0x20, 0x6b, 0xcd, 0x36, 0x16, 0x64, 0xc8, 0xf8, 0xc8, 0x80, 0x57,
	0xb1, 0x76, 0xff, 0xda, 0x82, 0x05, 0x1d, 0x0e, 0x95, 0xe2, 0xb5, 0x01, 0x48, 0xf7, 0xd6, 0xfb,
	0x76, 0x4c, 0xe8, 0x6b, 0xaf, 0xe1, 0xa0, 0x87, 0x70, 0x6b, 0x92, 0xaa, 0xc3, 0x50, 0x5f, 0x4c,
	0x3d, 0x53, 0x0d, 0x07, 0xca, 0xe7, 0xc9, 0x87, 0x03, 0xe5, 0x43, 0x3c, 0x03, 0x57, 0x98, 0x56,
	0x78, 0x40, 0xa3, 0x2c, 0x14, 0x38, 0x26, 0x2c, 0x4b, 0xc3, 0x91, 0x09, 0xe6, 0x40, 0x25, 0xa2,
	0x9e, 0x19, 0x5c, 0x42, 0x12, 0x9d, 0xc2, 0x5d, 0x5e, 0x9f, 0x06, 0x4a, 0xd1, 0x82, 0xca, 0xe8,
	0xfb, 0xa5, 0x8c, 0x6e, 0x48, 0x1b, 0x6f, 0x9a, 0x22, 0x37, 0x80, 0x25, 0x5d, 0x8a, 0x8d, 0x97,
	0xed, 0xde, 0x5d, 0x83, 0xe4, 0xb8, 0x77, 0x2f, 0x9a, 0xc0, 0x96, 0xdd, 0x04, 0xd6, 0xbd, 0x39,
	0xe6, 0xca, 0x59, 0xe9, 0xfe, 0xdb, 0x81, 0x6f, 0xa8, 0x5a, 0xfb, 0xb5, 0x7b, 0xe6, 0xfd, 0xa7,
	0x0d, 0xfd, 0x9a, 0x93, 0xe7, 0x90, 0x36, 0x51, 0x6c, 0x9c, 0x6a, 0xb1, 0x29, 0x26, 0x3a, 0xad,
	0xaf, 0x30, 0xd1, 0x99, 0x7b, 0x2d, 0x13, 0x9d, 0xf9, 0xff, 0xc3, 0x44, 0xa7, 0xfd, 0xfa, 0x26,
	0x3a, 0x0b, 0xff, 0xe3, 0x44, 0xe7, 0xca, 0x6b, 0x98, 0xe8, 0x2c, 0xbe, 0xc6, 0x89, 0x4e, 0xe7,
	0x52, 0x13, 0x9d, 0x8f, 0x4b, 0x13, 0x1d, 0x50, 0xf9, 0xff, 0xa0, 0xdc, 0x9d, 0x4e, 0x4b, 0xb0,
	0xd9, 0x63, 0x9d, 0xee, 0xec, 0xb1, 0xce, 0xd2, 0x94, 0xb1, 0xce, 0xd5, 0xca, 0x58, 0xe7, 0x1f,
	0x0e, 0x2c, 0x2b, 0x9b, 0x76, 0x19, 0x0e, 0x55, 0x87, 0x27, 0xb1, 0x82, 0x9b, 0xfe, 0xf5, 0x78,
	0x94, 0x90, 0xbc, 0x82, 0xdb, 0x34, 0xf4, 0x00, 0xae, 0x15, 0x6b, 0x0d, 0xc9, 0x39, 0xaa, 0x57,
	0xe8, 0x1a, 0x03, 0x6c, 0xda, 0x27, 0x19, 0x8e, 0x05, 0x15, 0x79, 0xb5, 0x6d, 0xe0, 0xca, 0x7d,
	0x7e, 0xde, 0x6d, 0xaa, 0x30, 0xcb, 0xaf, 0xcc, 0xc4, 0x7c, 0x03, 0x57, 0x1e, 0xf9, 0x94, 0xf1,
	0xa7, 0x98, 0x86, 0x34, 0x1e, 0x9a, 0x58, 0xb6, 0x28, 0xee, 0x6f, 0x1d, 0xe8, 0x14, 0x47, 0x96,
	0x4f, 0xb5, 0x04, 0xa7, 0xe9, 0xc0, 0x67, 0x3c, 0x3f, 0xea, 0x98, 0x20, 0xcf, 0x29, 0x68, 0x44,
	0x94, 0xaf, 0x07, 0xc4, 0x67, 0x71, 0x90, 0xe6, 0xe7, 0x9c, 0xa4, 0xa3, 0xf7, 0xa1, 0xa3, 0x1e,
	0x15, 0x0a, 0xfb, 0xe7, 0xd4, 0xdd, 0xdf, 0xad, 0xde, 0x7d, 0xe1, 0x67, 0x6f, 0x2c, 0xed, 0xfe,
	0xc9, 0x01, 0x78, 0x2c, 0x04, 0xf6, 0xcf, 0x5f, 0xe2, 0x0b, 0x22, 0x1f, 0xa3, 0x91, 0xaa, 0x58,
	0x4f, 0x39, 0x8b, 0x54, 0xd3, 0x6b, 0x2c, 0x9b, 0x24, 0xa3, 0x43, 0x58, 0x4a, 0x13, 0xe2, 0x53,
	0x92, 0xe6, 0xa8, 0x2a, 0x3f, 0xfb, 0x76, 0xf9, 0xb1, 0x52, 0x28, 0xde, 0x18, 0x58, 0xb2, 0xfa,
	0x1d, 0x54, 0xda, 0xde, 0xff, 0x10, 0xae, 0x57, 0x44, 0xec, 0x06, 0xbf, 0x33, 0xab, 0xc1, 0xff,
	0xbd, 0x03, 0x4b, 0xbb, 0x19, 0xe6, 0xc1, 0x80, 0x85, 0x01, 0x25, 0x5c, 0xbe, 0x5e, 0xcd, 0x17,
	0x8c, 0x82, 0x7c, 0xa9, 0x4a, 0xfd, 0x94, 0x21, 0x4d, 0x3d, 0xb3, 0x69, 0xd7, 0x67, 0x45, 0x83,
	0x50, 0x3b, 0x8f, 0x59, 0x81, 0x05, 0x41, 0x70, 0x54, 0x4c, 0x63, 0xcc, 0xca, 0xfd, 0xfb, 0x3c,
	0x5c, 0x57, 0xb7, 0xb2, 0x1f, 0x53, 0xa1, 0x9f, 0x9a, 0x82, 0x28, 0x9b, 0x15, 0x31, 0xc7, 0xfa,
	0x7c, 0x89, 0xde, 0x81, 0xc5, 0x73, 0xd3, 0x4c, 0x1b, 0x57, 0xdf, 0x2a, 0xb9, 0x3a, 0xef, 0xb4,
	0xbd, 0x42, 0x0c, 0x3d, 0x81, 0x6b, 0x89, 0x55, 0xbb, 0xad, 0xe0, 0xb8, 0x53, 0xf3, 0xd6, 0xd6,
	0x42, 0x5e, 0x65, 0x0b, 0x62, 0xb0, 0x9a, 0x36, 0x56, 0x28, 0xa5, 0x74, 0x5e, 0x29, 0xfd, 0xce,
	0x2c, 0xb4, 0xc9, 0x1b, 0x8e, 0x19, 0xea, 0xd0, 0x0f, 0x61, 0x31, 0x35, 0x2f, 0x69, 0x33, 0xa5,
	0xba, 0x3b, 0xe5, 0x99, 0xed, 0x15, 0xc2, 0xe8, 0x01, 0xcc, 0x0f, 0x19, 0xd6, 0x13, 0xaa, 0xc9,
	0xd1, 0x56, 0x91, 0x01, 0x9e, 0x92, 0x91, 0x50, 0x13, 0x50, 0x1c, 0xb1, 0x38, 0x50, 0x8d, 0xaa,
	0x41, 0xfd, 0x12, 0x4d, 0x26, 0x68, 0x2a, 0x30, 0xd7, 0x02, 0x1a, 0xd2, 0xc7, 0x04, 0xf4, 0x21,
	0x2c, 0xe3, 0x22, 0xbe, 0x95, 0x1f, 0x3a, 0xca, 0x0f, 0xb7, 0x1b, 0x52, 0xc0, 0x9b, 0x10, 0x97,
	0xf7, 0x33, 0xb4, 0x02, 0x56, 0xa9, 0x80, 0x9a, 0xfb, 0xb1, 0xa3, 0xda, 0xab, 0x6c, 0x91, 0x3d,
	0x82, 0xa0, 0xfe, 0x39, 0x11, 0xda, 0x4e, 0x8d, 0xd3, 0x36, 0xc9, 0x7d, 0x0f, 0xd0, 0x2e, 0xc7,
	0xc9, 0xd9, 0x20, 0xf3, 0x7d, 0x92, 0xa6, 0xac, 0xd8, 0x17, 0x52, 0xf9, 0xac, 0x8e, 0x05, 0x89,
	0xf5, 0x1b, 0xb3, 0xed, 0xd9, 0x24, 0xf7, 0xcf, 0x0e, 0xac, 0x54, 0x37, 0xee, 0x50, 0x5f, 0xa0,
	0x17, 0xd0, 0x0d, 0xa8, 0x5f, 0xda, 0xdc, 0xdd, 0x7c, 0x58, 0x36, 0xbb, 0x76, 0xe7, 0xc6, 0xce,
	0x78, 0x9b, 0xc6, 0x01, 0x5b, 0x51, 0xff, 0x17, 0x70, 0x6d, 0x52, 0xa0, 0xe6, 0x99, 0xff, 0xae,
	0x8d, 0x02, 0x93, 0xa3, 0x85, 0xea, 0x77, 0x6d, 0x98, 0xf8, 0x8b, 0x03, 0xb7, 0xd4, 0x43, 0x95,
	0x67, 0x89, 0x38, 0x36, 0x73, 0x9e, 0x43, 0x9c, 0x9e, 0xa3, 0x9f, 0xc1, 0xd5, 0x0b, 0x9a, 0x52,
	0x41, 0x82, 0x5d, 0xce, 0xb2, 0x24, 0x35, 0x87, 0x7a, 0xb7, 0xa4, 0xbc, 0x76, 0xeb, 0xc6, 0x0b,
	0x7b, 0x9f, 0x3e, 0x55, 0x59, 0x57, 0x9f, 0x00, 0xaa, 0x0a, 0xd5, 0x9c, 0xec, 0xfd, 0xf2, 0xc9,
	0xde, 0xba, 0x84, 0x47, 0xed, 0xd3, 0xfd, 0xa1, 0x05, 0x37, 0x6a, 0x26, 0x44, 0xf2, 0x99, 0x92,
	0x12, 0x7e, 0x41, 0x82, 0xed, 0x2c, 0x15, 0x2c, 0x22, 0xdc, 0x14, 0xa7, 0x09, 0xaa, 0x6c, 0xef,
	0x03, 0x9a, 0x9e, 0xc9, 0xf0, 0xca, 0x47, 0xf3, 0xf9, 0x1a, 0x9d, 0x01, 0xb2, 0x86, 0xe5, 0xaa,
	0x03, 0x21, 0x81, 0x99, 0x83, 0x3d, 0x9a, 0x35, 0xa3, 0xda, 0xd8, 0xaf, 0x6c, 0xd5, 0x7e, 0xaa,
	0xd1, 0x29, 0x8b, 0xd0, 0x29, 0x27, 0xe4, 0x39, 0x0f, 0x08, 0x37, 0xd3, 0x27, 0x9d, 0x7d, 0x93,
	0xe4, 0xfe, 0x13, 0xb8, 0xdd, 0xa0, 0xf8, 0xab, 0x0c, 0x87, 0x4e, 0x16, 0xd4, 0xdf, 0xc9, 0x3f,
	0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x8a, 0xcb, 0x7a, 0x61, 0x1e, 0x00, 0x00,
}
