package models

const (
	TBL_PLAYER                           = "player"
	TBL_PLAYER_LOGIN                     = "player_login"
	TBL_PLAYER_BULK_SYNC_DATA            = "player_bulk_sync_data"
	TBL_MAILBOX                          = "mailbox"
	TBL_MAILBOX_TRANSCRIPT_EN_US         = "mailbox_transcript_en_us"
	TBL_MISSION                          = "mission"
	TBL_PLAYER_MISSION_BINDING           = "player_mission_binding"
	TBL_PLAYER_QUEST_BINDING             = "player_quest_binding"
	TBL_QUEST                            = "quest"
	TBL_INGREDIENT                       = "ingredient"
	TBL_INGREDIENT_PROGRESS              = "ingredient_progress"
	TBL_RECIPE                           = "recipe"
	TBL_RECIPE_INGREDIENT_BINDING        = "recipe_ingredient_binding"
	TBL_KNAPSACK                         = "knapsack"
	TBL_MISSION_REWARD_BINDING           = "mission_reward_binding"
	TBL_LEGAL_CURRENCY_PAYMENT_RECORD    = "legal_currency_payment_record"
	TBL_BUILDABLE                        = "buildable"
	TBL_BUILDABLE_LEVEL_BINDING          = "buildable_level_binding"
	TBL_BUILDABLE_LEVEL_DEPENDENCY       = "buildable_level_dependency"
	TBL_BUILDABLE_INGREDIENT_INTERACTION = "buildable_ingredient_interaction"
	TBL_PLAYER_RECIPE                    = "player_recipe"
	TBL_STAGE_INITIAL_STATE              = "stage_initial_state"
	TBL_PLAYER_STAGE_BINDING             = "player_stage_binding"
	TBL_PLAYER_INGREDIENT_FOR_IDLE_GAME  = "player_ingredient_for_idlegame"
	TBL_PERSISTENT_CAPTCHA  = "persistent_captcha"
)
